<a href="https://colab.research.google.com/github/mobius29er/AIML_Class/blob/main/colab_activity21_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Colab Activity 21.1: A Simple Network

**Expected Time = 60 minutes**

This activity focuses on the basics of an artificial neural network (ANNs).  Using the titanic dataset you will work through the basic steps of the neural network's forward pass.  This means adding a bias feature, creating weights, applying the weights and activation function, and making predictions using the results of a sigmoid activation.

#### Index

- [Problem 1](#-Problem-1)
- [Problem 2](#-Problem-2)
- [Problem 3](#-Problem-3)
- [Problem 4](#-Problem-4)
- [Problem 5](#-Problem-5)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Creating the Data

Below, we load in the titanic dataset from `seaborn`.  Note that this dataset has missing values in the `age` column that are subsequently dropped.  This exercise only uses the top five rows as that dataset in order to clarify the initial workings of ANNs

In [2]:
import seaborn as sns

In [3]:
titanic = sns.load_dataset('titanic').dropna(subset = ['age'])

In [4]:
X = titanic[['age', 'fare']].head()
y = titanic['survived'].head()

### Problem 1

#### Adding the Bias Feature

Complete the function `add_bias` below to add a column of ones which will act as the bias feature for the data `X`.

As a convention, add the bias column as the first column in the dataset.

In [7]:
def add_bias(X):

    bias = pd.Series(np.ones(X.shape[0]), index=X.index)
    X_with_bias = pd.concat([bias, X], axis=1)

    return X_with_bias


### ANSWER CHECK
X_with_bias = add_bias(X)
X_with_bias.head()

     0   age     fare
0  1.0  22.0   7.2500
1  1.0  38.0  71.2833
2  1.0  26.0   7.9250
3  1.0  35.0  53.1000
4  1.0  35.0   8.0500

[Back to top](#-Index)

### Problem 2

#### A Single Node Weights



The first step when defining an ANN is to assign a weight for each input of each node.  

Assuming the ANN used in this exercise uses one single node, this amounts to creating three initial weights -- one for the bias, and one weight for each feature.  

Below, use a `random.seed(42)` for reproducibility. Next, use the random normal number generator from `NumPy` to generate an array of three weights for the bias and the features.  Assign this array to the variable `weights`.

In [8]:

weights = ''

weights = np.random.seed(42)
weights = np.random.randn(3)


### ANSWER CHECK
print(weights.shape)
print(weights)

(3,)
[ 0.49671415 -0.1382643   0.64768854]

[Back to top](#-Index)

### Problem 3

#### Computing the weighted sum



Next, you are to use the weights to apply them to the features and bias.

Below, use matrix multiplication to apply the `weights` to your data `X_with_bias` and assign the results to `weighted_sum` below.

In [9]:

weighted_sum = ''

weighted_sum = X_with_bias.dot(weights)

### ANSWER CHECK
weighted_sum

0     2.150641
1    41.412047
2     2.034774
3    30.049725
4     0.871356
dtype: float64

[Back to top](#-Index)

### Problem 4

#### Sigmoid Activation



After computing the weighted sum for the data you are to apply a sigmoid activation function.  Below, complete the definition of the `sigmoid` function that takes in an array of values and returns the result of applying the transformation:

$$f(x) = \frac{1}{1 + e^{-x}}$$

Finally, apply the `sigmoid` function to the array `weighted_sum` and assign the results to the variable `output`.

In [11]:
from typing import AnyStr

def sigmoid(X):

    '''
    This function returns the sigmoid
    defined as 1/(1 + e^-x).
    '''
    return 1 / (1 + np.exp(-X))

output = sigmoid(weighted_sum)


### ANSWER CHECK
output

0    0.895729
1    1.000000
2    0.884400
3    1.000000
4    0.705028
dtype: float64

[Back to top](#-Index)

### Problem 5

#### Making Predictions



Recall that the output of the sigmoid can be interpreted as a probability of being a member of the positive class -- survived.   Use the `output` variable to make predictions for your first pass through the neural network.  What is the accuracy of your predictions?  Assign the predictions as `preds` and accuracy as `starting_acc`.

In [12]:
preds = (output >= 0.5).astype(int)
starting_acc = (preds == y).mean()


### ANSWER CHECK
print(preds)
print(starting_acc)

0    1
1    1
2    1
3    1
4    1
dtype: int64
0.6

Great job!  Next you will examine a more complex network.